# Generated by Django 5.0.7 on 2024-07-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
